### ISSUE TITLE
Error compiling under CCE (Cray compiler)

### ISSUE THREAD

**Issue by michalakes** [NOAA-EMC/NCEPLIBS-w3emc#135]
This bug report is relative to hash 8bb34eb3ee0 though it appears to have been an issue for some time previous.

Cray compiler reports an issue with argument number mismatch in the call to FI8503 at line 2094 of w3fi85.f (see screenshot, below).  Subroutine is defined with 9 arguments but the call at line 2094 has only 8 arguments.  

Here is the error message:

ftn-1295 crayftn: ERROR FI8509, File = ../../../../../home/michalak/CCE-NCEPlibs/NCEPLIBS-w3emc/src/w3fi85.f, Line = 2094, Column = 11
  "FI8503" is defined or referenced at line 1305 (/p/home/michalak/CCE-NCEPlibs/NCEPLIBS-w3emc/src/w3fi85.f) and here.  The number of arguments do not match.  Expected 9, but found 8.

_Request_:  Do you have a suggested workaround value for the missing first argument in the call?

Thanks, 

John 

![w3fi85 f](https://user-images.githubusercontent.com/8060975/141868672-35f8457b-6dc9-4abb-a0b5-0f756fbf4815.png)

**Comment by kgerheiser** [comment]
I wonder if that's a typo? All other uses of that subroutine pass `kary(11)` as the first argument.

**Comment by michalakes** [comment]
Thanks, I'll use that as a workaround for time being.  Probably needs to be updated in the repo. (Intel compiler is too forgiving sometimes.  Cray is more pedantic.)

**Comment by GlennCreighton** [comment]
Hi, I just ran into the same issue, FYSA, I also deduced it needed kary(11), but wanted to note it here so it could be added to your next release.

**Comment by kgerheiser** [comment]
This is some ugly code. `kary(11)` seems like the correct value, but I don't really know what it does. There are 3 other instances of the exact some code copy/pasted which contains `kary(11)`.

Put in a PR with #143

**Comment by kgerheiser** [comment]
@GlennCreighton are you also using Cray compilers?

**Comment by GlennCreighton** [comment]
So, pretty safe bet it is the appropriate value.  It compiles anyway!  Thanks.
    On Wednesday, March 30, 2022, 03:30:29 PM CDT, Kyle Gerheiser ***@***.***> wrote:  
 
 


This is some ugly code. kary(11) seems like the correct value, but I don't really know what it does. There are 3 other instances of the exact some code copy/pasted which contains kary(11).

**Comment by GlennCreighton** [comment]
Yes, should I feed back the required changes?  There's not many for this baseline.
I have six other baselines I'm adding Cray support to if that would be helpful to others (ip, sp, bacio, w3emc, w3nco, grib_util).  I'm still working on ip and grib_util as I'm getting undefined references to ipolate routines when compiling copygb and copygb2 right now, but the rest of it compiles.
    On Wednesday, March 30, 2022, 03:33:32 PM CDT, Kyle Gerheiser ***@***.***> wrote:  
 
 


@GlennCreighton are you also using Cray compilers?

**Comment by kgerheiser** [comment]
If you've got changes that add support for Cray compilers then sure.

A hint for building grib_util may be using ip v3.3.3 (instead of develop, v4.0.0). There are some breaking changes in the new version of ip that aren't compatible with the current version of grib_util.

**Comment by GlennCreighton** [comment]
Hey, thank you for that.
    On Wednesday, March 30, 2022, 03:48:17 PM CDT, Kyle Gerheiser ***@***.***> wrote:  
 
 


If you've got changes that add support for Cray compilers then sure.

A hint for building grib_util may be using ip v3.3.3 (instead of develop, v4.0.0). There are some breaking changes in the new version of ip that aren't compatible with the current version of grib_util.

**Comment by GlennCreighton** [comment]
Great, that worked, I'm creating local patches and would like to use the most up-to-date versions available, is there a ticket describing the issue with ip 4.0.0?  I saw some issues during compile with abs being used instead of fabs that I did not see during compile of 3.3.3.  In any case, thanks for the pro tip, that one's been bugging me.
