### ISSUE TITLE
release version 2.9.3

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-w3emc#136]
@kgerheiser did you do a release of w3emc after combining the w3nco functions?

If not, we need to do one...

Since this involves big changes, perhaps we should call the next release 3.0.0?

**Comment by kgerheiser** [comment]
The 2.8.0 release already contains the w3nco functions.

**Comment by edwardhartnett** [comment]
OK, awesome. I didn't look that far back in the release notes... ;-)

**Comment by edwardhartnett** [comment]
Looks like we need a new release due to https://github.com/NOAA-EMC/NCEPLIBS-w3emc/issues/137

**Comment by kgerheiser** [comment]
Looks like the commit is in release 2.9.2

**Comment by edwardhartnett** [comment]
I thought I needed this release to solve a problem on g2, but I was wrong.

However, there are some important changes and this should be released soon. See the release notes for details.

**Comment by edwardhartnett** [comment]
Released.
