### ISSUE TITLE
Legacy syntax for MAX0, MIN0 generates compiler error with GNU 11.1.0

### ISSUE THREAD

**Issue by natalie-perlin** [NOAA-EMC/NCEPLIBS-w3emc#142]
Legacy syntax in ./src/w3ai00.f that uses MAX0 and MIN0 instead of MAX, MIN causes compiler error with the GNU gfortran 11.1.0. The line is

./src/w3ai00.f:168:           N = MAX0(-127_8,MIN0(127_8,N))

This could be overcome by passing additional flags during the compilation, such as -fdefault-integer-8 -fdefault-real-8, but these flags need to be tailored properly for the builds in different directories, such as /build/src/include_4, /build/src/include_8  (which is slightly more than trivial task for the average user...)

The bug is documented in the following tickets:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100755
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100283

**Comment by kgerheiser** [comment]
Transferred this issue to w3emc because the libraries have been combined, and this repo now contains the former w3nco code.

**Comment by edwardhartnett** [comment]
@natalie-perlin unfortunately Kyle is no longer working at the EMC. 

Do you think his proposed solution would work?

**Comment by edwardhartnett** [comment]
@natalie-perlin I am soon to do a new release of this library. If I implement Kyle's suggested solution, can you test it?

**Comment by edwardhartnett** [comment]
Actually, this change was apparently made long ago and is included in the current release. SO this issue should be fixed. Please reopen this issue if there are further problems.
