### ISSUE TITLE
question libw3emc

### ISSUE THREAD

**Issue by fipoucat** [NOAA-EMC/NCEPLIBS-w3emc#145]
I am building a program that needs libw3emc_i4r8 while my compilation gives me libw3emc_4.a. What the difference and if so how to get:  and libw3emc_i4r8.

Thank you

**Comment by kgerheiser** [comment]
`libw3emc_d.a` is what you want. It provides a real64, int32 interface.

`_4` is real32, int32.

`_8` is real64, int64.

**Comment by fipoucat** [comment]
You are right I have libw3emc_d.a and libw3nco_d.a

and beow the error message I am having:
gfortran -I../../libs/mods/g2  tave.f -L../../libs -lw3emc_i4r8
-lw3nco_i4r8 -lbacio -lg2 -L/home/parallels/MET111/external_libs/lib
-ljasper -lz -lpng -o ../../trk_exec/tave.exe
/usr/bin/ld: cannot find -lw3emc_i4r8
/usr/bin/ld: cannot find -lw3nco_i4r8
collect2: error: ld returned 1 exit status
make[2]: [Makefile:12: ../../trk_exec/tave.exe] Error 1 (ignored)

can I do a symbolic link: ln  -s ?

**Comment by kgerheiser** [comment]
Sure, that'll work. Or replace `-lw3emc_i4r8`with `-lw3emc_d`.

**Comment by fipoucat** [comment]
OK, thank you
