### ISSUE TITLE
lib needs to be corrected to `CMAKE_INSTALL_LIBDIR`

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-w3emc#146]
https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/264565a9b85288fd55ed262ddfb7d6c3d9732ef0/src/CMakeLists.txt#L55

On x64, the library is installed in `lib64` while the cmake config file is in `lib`.

Note.
Its likely this is happening in other nceplibs as well.

**Comment by edwardhartnett** [comment]
@aerorahul what should be done about this? Sorry, I'm not the CMake expert that Kyle was...

**Comment by aerorahul** [comment]
The above line should be replaced with:
```
set(CONFIG_INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME})
```
i.e. `lib` should be replaced with `${CMAKE_INSTALL_LIBDIR}`

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett @aerorahul I'm just getting caught up on this. To be clear, is the goal to have the cmake config land in the same directory as the library? In the case of bacio, the static library destination is being set in src/CMakeLists.txt in the "ARCHIVE DESTINATION lib" line, so using CMAKE_INSTALL_DIR will not guarantee that the cmake files end up in the same directory.

**Comment by edwardhartnett** [comment]
Let's talk about bacio under the bacio project. ;-)
