### ISSUE TITLE
NCEP grids 172 and 220 not defined correctly in w3fi71.f

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/NCEPLIBS-w3emc#157]
A user - @malloryprow - attempted to interpolate a 0.25-degree GFS Grib1 file to NCEP grids 172 and 220 using `copygb` as follows:

```
copygb -g172 -x $gfs_input.grb 172.output.grb
copygb -g220 -x $gfs_input.grb 220.output.grb
```

The output was not on the expected grid because the grid specifications are not being defined properly in `w3fi71.f`. A look at the prolog comments for this routine indicate the definition of the orientation angle for these grids has changed multiple times over the years.

More details of the problem and a solution will be provided.

**Comment by GeorgeGayno-NOAA** [comment]
This version of copygb was used (on Cactus):
`/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/copygb`

**Comment by GeorgeGayno-NOAA** [comment]
The grid 172 specifications according to the NCEP grib1 documentation are:
https://www.nco.ncep.noaa.gov/pmb/docs/on388/tableb.html#GRID172

To match the documentation, the routine's corner point latitude and orientation angle must be updated to -36.899 and -80.0 respectively:

```
--- a/src/w3fi71.f
+++ b/src/w3fi71.f
@@ -720,7 +720,7 @@ C
      &    -703,   128, 703, 0, 0, 0, 0, 0, 0/
       DATA  GRD171/ 0, 255, 5, 770,930,  25032, -119560,   0,  -80000,
      &   12700,  12700, 0, 64, 0, 0, 0, 0, 0/
-      DATA  GRD172/ 0, 255, 5, 690,710, -36866, -220194,   0, -260000,
+      DATA  GRD172/ 0, 255, 5, 690,710, -36899, -220194,   0,  -80000,
      &   12700,  12700, 128, 64, 0, 0, 0, 0, 0/
       DATA  GRD173/ 0, 255, 0,4320,2160, 89958,      42, 128,  -89958,
```

**Comment by GeorgeGayno-NOAA** [comment]
NCEP grid 220 is just a coarser version of grid 172. 
https://www.nco.ncep.noaa.gov/pmb/docs/on388/tableb.html#GRID220

Note that the documentation has the wrong orientation angle. It should be the same as grid 172 (80.0W). And according to Bob Grumbine, the corner point latitude should be -36.899, the same as in grid 172.

Therefore, w3fi71.f should be updated as follows for grid 220:

```
       DATA  GRD219/ 0, 255, 5, 385,465,  25032, -119560,   0,  -80000,
      &   25400,  25400, 0, 64, 0, 0, 0, 0, 0/
-      DATA  GRD220/ 0, 255, 5, 345,355, -36866, -220194,   0, -260000,
+      DATA  GRD220/ 0, 255, 5, 345,355, -36899, -220194,   0,  -80000,
      &   25400,  25400, 128, 64, 0, 0, 0, 0, 0/
       DATA  GRD221/ 0, 255, 3, 349,277,   1000, -145500,   8, -107000,
```

**Comment by edwardhartnett** [comment]
Can we also add tests that confirm this change?

**Comment by Hang-Lei-NOAA** [comment]
a bugfix branch is created to make change and test it.

**Comment by GeorgeGayno-NOAA** [comment]
> Can we also add tests that confirm this change?

I see there is a test script for copygb. I can help add a simple test case for both grids.

**Comment by GeorgeGayno-NOAA** [comment]
An illustration of the problem. Run copygb to convert a GFS GRIB1 0.25-degree file as follows:

```
copygb -g172 -x $gfs_input.grb 172.output.grb
copygb -g220 -x $gfs_input.grb 220.output.grb
```

Both grids should have the south pole at approximately the center. Instead, the grid covers parts of Australia and the tropics. Here are plots of the tranformed land mask:



![Grid_172_wrong](https://user-images.githubusercontent.com/52789452/212091116-5330030e-1ba0-4e1e-8bf4-34509453895f.png)
![Grid_220_wrong](https://user-images.githubusercontent.com/52789452/212091143-3388f344-034d-409a-936f-9dd4b860678a.png)

**Comment by GeorgeGayno-NOAA** [comment]
The grid specifications in w3fi71.f may be overridden by passing them in as arguments to `copygb`. 

Invoke `copygb` with the correct grid specs as follows:

```
GRID 172
copygb '-g255 5 690 710 -36899 139806 0 -80000 12700 12700 128 64 0 0 0 0 0' -x $gfs_input.grb 172.output.grb
```

```
GRID 220
copygb '-g255 5 345 355 -36899 139806 0 -80000 25400 25400 128 64 0 0 0 0 0' -x $gfs_input.grb 220.output.grb
```

**Comment by Hang-Lei-NOAA** [comment]
@GeorgeGayno-NOAA if you already have the test, then please you lead this. Make a branch in your fork, and add these, then push back. Thanks

**Comment by GeorgeGayno-NOAA** [comment]
> The grid specifications in w3fi71.f may be overridden by passing them in as arguments to `copygb`.
> 
> Invoke `copygb` with the correct grid specs as follows:
> 
> ```
> GRID 172
> copygb '-g255 5 690 710 -36899 139806 0 -80000 12700 12700 128 64 0 0 0 0 0' -x $gfs_input.grb 172.output.grb
> ```
> 
> ```
> GRID 220
> copygb '-g255 5 345 355 -36899 139806 0 -80000 25400 25400 128 64 0 0 0 0 0' -x $gfs_input.grb 220.output.grb
> ```

The geo-referencing of the grids is now correct:


![Grid_172_correct](https://user-images.githubusercontent.com/52789452/212104379-7e7d5cf5-bd04-48ba-bb8e-f28257657a04.png)
![Grid_220_correct](https://user-images.githubusercontent.com/52789452/212104405-bd55518e-5cf4-4691-8ee5-7507a240db5f.png)
