### ISSUE TITLE
W3AS00 is not provided in installation

### ISSUE THREAD

**Issue by kadircs** [NOAA-EMC/NCEPLIBS-w3emc#219]
`subroutine W3AS00` is in `src/w3as00.f` but it is not installed. The latest [w3emc](https://github.com/NOAA-EMC/NCEPLIBS-w3emc/commit/1ed2ba2941d486975ad8af784e93c43ae11abce0) requires `W3AS00`. Would you please help?

**Comment by edwardhartnett** [comment]
Build with -DWITH_EXTRA_DEPS=ON
