### ISSUE TITLE
Merge in code from w3nco

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-w3emc#33]
As discussed in an NCEPLIBS issue, we will combine the code from w3nco into this library, and then remove w3nco from NCEPLIBS. See https://github.com/NOAA-EMC/NCEPLIBS/issues/124

**Comment by BoiVuong-NOAA** [comment]
Hi Ed,

Do you have a due date for this  task ?  we are very busy with delivery 
gfs v16 by the COB 10/9.

Thanks,

Boi

**Comment by edwardhartnett** [comment]
Finish delivery of GFS v16 first for sure.

**Comment by Hang-Lei-NOAA** [comment]
I have started a local merge on dell.
Once it is tested fine, I will create a branch on w3emc repo, and also
submit it to code manager Boi for testing.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA and @BoiVuong-NOAA any updates on this?

**Comment by BoiVuong-NOAA** [comment]
No, Hang and I are working on WCOSS2.

**Comment by Hang-Lei-NOAA** [comment]
This have been merged and created a branch w3 on w3emc repo. The test of w3
on dell and Hera was fine.

**Comment by edwardhartnett** [comment]
Guys, are you going to put up a PR for this work?

**Comment by Hang-Lei-NOAA** [comment]
Need to discuss if this will be merged into w3emc or creating a individual
repo.

**Comment by edwardhartnett** [comment]
It will be merged into w3emc.

We already have too many repos! Adding one is the opposite of what we want to do. ;-)

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA what do you think about the interdependence issue?

Should we wind back these changes, write tests for both packages, and then try again?

**Comment by Hang-Lei-NOAA** [comment]
Some dependencyship  if they are not required or just optional. Then we can
remove them.
