### ISSUE TITLE
So very many more tests needed

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-w3emc#37]
We seem to have 7 lines of test code. ;-)

Well that's not enough, is it?

**Comment by edwardhartnett** [comment]
OK, no more bumping this to the next release.

**Comment by kgerheiser** [comment]
~~This is going to be a huge task given the quality of the code.~~

Thought this was #78 and meant to put that comment in there, but it still applies.

**Comment by edwardhartnett** [comment]
I keep hearing that GRIB1 will go away, but I'm starting to wonder if it will. Right now it's "only" used for the aviation forecast.

Well, that seems like a pretty important application. I'm no atmospheric scientist, but I'm pretty sure that weather forecasts are pretty important to the tens of thousands of people in the air every day.

Let's start by adding tests to all code touched in any PR. That will start to build up the tests.

Warnings should not be attempted until we have more testing. It's too easy to accidentally break code. 

Anyway, here we are, doing releases of this super-important code without even a test to bless ourselves with.

**Comment by edwardhartnett** [comment]
OK, some tests have been added, but we are still at only 2% test coverage. I've added a bunch of specific test issues.
