### ISSUE TITLE
identify areas for testing

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-w3emc#46]
We must identify some tests to write.

Since we have zero, this should be pretty easy!

Let's get some specific issues in for test writing, then we can close this issue and start writing tests!

;-)

**Comment by edwardhartnett** [comment]
We need a collection of small (<50 MB) files GRIB1 files, committed to the repo. gipgd() is an important subroutine for early testing.

@BoiVuong-NOAA and @Hang-Lei-NOAA will generate some data files. Then they will start writing test.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA and @Hang-Lei-NOAA can we get some progress on this please?

**Comment by aerorahul** [comment]
@edwardhartnett 
Can we make a practice to not add binary files to the repos? 
They are incredibly hard to manage and bloats the repo size over time as new versions of the files get added. 
My 2c.

**Comment by edwardhartnett** [comment]
Yes, the plan is to put these test files on the FTP site.

**Comment by aerorahul** [comment]
Thats great.  The comment above made it seem like they were being committed to the repo.

**Comment by Hang-Lei-NOAA** [comment]
We are making progress.
As for the gblevents testing part, I rerun the global_workflow. But, the
GFS model produced data is too large to use.
I turn to writing a small file as test data to the code by a new code.

**Comment by edwardhartnett** [comment]
OK, that new code that produces the test file should be part of the repo. Does the new code also use w3emc code to write the file?

Or does it use some other library?

**Comment by Hang-Lei-NOAA** [comment]
No, It is just to revise a datafile. The datafile can be various that only
need to match the format.
No need to be included.
Testing code needs to be included as a part of the unit  test.

**Comment by edwardhartnett** [comment]
Hang-Lei-NOAA is making a small GRIB1 file that will be uploaded to the FTP site. He will also add some tests.

**Comment by edwardhartnett** [comment]
Any progress on this issue?

**Comment by Hang-Lei-NOAA** [comment]
The main data file has been made. Found new trouble in testing
gblevents under a simple unit test.
The practical use of gblevents is under production environment, which
requires several other files produced or system data outputted from the
running environment.
This is a challenge for us to do it in the independent environment. Unit
test can only choose a part of functions to test.
However, how to pick these functions out of w3emc without changing the
existing library is another question.

**Comment by edwardhartnett** [comment]
What is the progress here? Do we have a test yet?

**Comment by BoiVuong-NOAA** [comment]
Last updated from Hang, He is still working on gblevents routine. I am working on testing for routines in w3nco.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA w3nco is being retired, and all code from there has been moved to w3emc. So that's where you should be writing tests, right?

**Comment by BoiVuong-NOAA** [comment]
Yes, The w3nco combined into w3emc.  There will be one unit_test for w3nco and one is for w3emc.

**Comment by edwardhartnett** [comment]
OK, it has been three months since this issue was opened, and there has been no apparent progress so far.

Let's discuss what changes can be made to enable some progress on testing this repo.

**Comment by BoiVuong-NOAA** [comment]
Works are in-progress to test number of routines in W3EMC.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA and @Hang-Lei-NOAA, tests need to be developed incrementally. If you have even one test working, please put it up as a PR.

**Comment by BoiVuong-NOAA** [comment]
OK, I will.  I am still working on a program which it tests about 9 routines in W3EMC and W3NCO.

**Comment by Hang-Lei-NOAA** [comment]
I will push a PR to change the code and upload my testing data for
gblevents.

**Comment by edwardhartnett** [comment]
Seems like Boi will not be able to complete this work due to some other task. I have taken him off this issue.

**Comment by Hang-Lei-NOAA** [comment]
I will upload my test once my Hera soft token issue is resolved. Everything
is kept on Hera.

**Comment by edwardhartnett** [comment]
Any progress on testing this repo?

**Comment by Hang-Lei-NOAA** [comment]
This combined code was tested fine in working with UFS model. It reproduces
the capability of separated w3emc and w3nco libs. On this level, it could
be pushed to use for community.

But, the Unit test, as previously Boi said in leading the development, is
involved with testing hundreds of functions/subroutines. It’s not a small
test packages to develop.

**Comment by edwardhartnett** [comment]
We need to pick something and start writing unit tests. Start with the smallest you can think of. It does not have to use Boi's tests if we can do something easier.

Does this package write and also read grib files? If so, how about a test which first writes, then reads, a simple grib file?

If this package only reads grib files, then how about finding a small sample file, and writing a test to ensure it can be correctly read?

**Comment by Hang-Lei-NOAA** [comment]
This is not single function library. It is actually a combinations pool for
all kinds of small supporting utility codes. These codes are mostly used
together with other libraries or functions. I will start a unit test for
testing some common used supporting codes.

**Comment by edwardhartnett** [comment]
OK, I have identified a bunch of test issues that can be started. I will close this issue.
