### ISSUE TITLE
Remove code for AIX

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-w3emc#53]
In start.f we have:

```
#if defined AIX
      subroutine startfake
#else  /* Default is for LINUX */
      subroutine start
#endif
      end subroutine
```

We can remove support for AIX everywhere. No only is it not used anywhere, but we do not have any access for testing.

This should be done after testing is in place.

**Comment by BoiVuong-NOAA** [comment]
We can remove start.F routine. It is no longer needed for AIX in w3emc.

**Comment by edwardhartnett** [comment]
THis has been done in a previous release.
