### ISSUE TITLE
unable to build against CMake-built netCDF C and Fortran libraries

### ISSUE THREAD

**Issue by pmspire** [NOAA-EMC/NCEPLIBS-w3emc#56]
Hi. I'm having trouble building this library, apparently due to CMake being unable to find installed prerequisites. I have built the netCDF C (v4.7.4) and Fortran (v4.5.3) libraries, as well as `bacio`, `w3nco`, `sigio`, and `nemsio`, using the CMake builds for each code. Here is output from my attempted build:

```
+ cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_PREFIX_PATH=$PREFIX ..
-- The Fortran compiler identification is Intel 18.0.3.20180410
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/intel/impi/2018.3.222/bin64/mpiifort - skipped
-- Checking whether /opt/intel/impi/2018.3.222/bin64/mpiifort supports Fortran 90
-- Checking whether /opt/intel/impi/2018.3.222/bin64/mpiifort supports Fortran 90 - yes
-- Found bacio: $PREFIX/lib/libbacio_4.a (found version "2.4.0")
-- Found w3nco: $PREFIX/lib/libw3nco_4.a (found version "2.4.0")
-- Found MPI_Fortran: /opt/intel/impi/2018.3.222/bin64/mpiifort (found version "3.1")
-- Found MPI: TRUE (found version "3.1") found components: Fortran
-- Found nemsio: $PREFIX/lib/libnemsio.a (found version "2.5.1")
-- Found sigio: $PREFIX/lib/libsigio.a (found version "2.3.0")
CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NetCDF", but
  CMake did not find one.

  Could not find a package configuration file provided by "NetCDF" with any
  of the following names:

    NetCDFConfig.cmake
    netcdf-config.cmake

  Add the installation prefix of "NetCDF" to CMAKE_PREFIX_PATH or set
  "NetCDF_DIR" to a directory containing one of the above files.  If "NetCDF"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

While `NetCDFConfig.cmake` is indeed not available under `$PREFIX`, I do have

```
% ls -1 $PREFIX/lib/cmake/netCDF/
netCDFConfig.cmake
netCDFConfigVersion.cmake
netCDF-FortranConfig.cmake
netCDF-FortranConfigVersion.cmake
netcdffTargets.cmake
netcdffTargets-debug.cmake
netCDFTargets.cmake
netCDFTargets-debug.cmake
```

I know very little about CMake, but it seems like netCDF changed their CMake project name from `NetCDF` to `netCDF` some time ago, and so thought that `netCDFConfig.cmake` might be the required file.

So, I made the following change to `w3emc` hoping to reflect the case difference:

```
% diff CMakeLists.txt.orig CMakeLists.txt
29c29
< find_package(NetCDF REQUIRED Fortran)
---
> find_package(netCDF REQUIRED Fortran)
```

The initial error then disappears, but my build then fails with a series of errors like

```
CMake Error at src/CMakeLists.txt:26 (add_library):
  Target "w3emc_8" links to target "NetCDF::NetCDF_Fortran" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

for several variants of `w3emc_*`. I'm guessing that there may also be changes related to the netCDF Fortran install that would need to be reflected in the `w3emc` CMake config, but I'm uncertain about how to proceed.

Can you offer any guidance on this? Thanks in advance.

**Comment by climbfuji** [comment]
I think what happened is that you checked out the code without the `--recursive` option. The `FindNetCDF.cmake` macro comes from a submodule called `CMakeModules`. If you just clone the NCEPLIBS-w3emc without `--recursive`, you have change to `NCEPLIBS-w3emc` and run `git submodule update --init --recursive`.

**Comment by pmspire** [comment]
@climbfuji Yes, thank you! I was trying to build from the release tarball https://github.com/NOAA-EMC/NCEPLIBS-w3emc/archive/v2.7.3.tar.gz (found via https://github.com/NOAA-EMC/NCEPLIBS-w3emc/releases/tag/v2.7.3), but switching to cloning the git repo, checking out the `v2.7.3` tag, and fetching the submodules solved the issue for me.

**Comment by kgerheiser** [comment]
We have removed the Git submodule for the CMake module. However, there hasn't been a release since then, so it still needs the submodule. We will do a release and then you will be able to download the release as a `.tar.gz` without needing to use git.
