### ISSUE TITLE
What to do with gblevents?

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-w3emc#71]
This routine causes a circular dependency with nemsio, and it also uses NetCDF, sigio, sp, and bufr. Without this w3emc would be dependency free. It definitely stands out among the other routines in this library.

Does it belong in the w3emc repo? Is there a more appropriate place to put it?

@Hang-Lei-NOAA @BoiVuong-NOAA

**Comment by Hang-Lei-NOAA** [comment]
This has been discussed before many times. It has to be there. obspro group
don't want to keep it, and it is the core part of GFS prep.

**Comment by edwardhartnett** [comment]
Well we have to resolve the circular dependency somehow...

**Comment by kgerheiser** [comment]
We shouldn't have circular dependencies. We can maintain the code, but does it _have_ to be in this repo? It doesn't seem like belongs here.

**Comment by edwardhartnett** [comment]
What is we combined nemsio with w3emc. Then everything would be in one place.

**Comment by Hang-Lei-NOAA** [comment]
No a good solution.
One is IO interface.
The other is utility package.
Someone used to suggested combined all libraries into one called NCEPbuild.
This was denied.

**Comment by kgerheiser** [comment]
That doesn't seem right to me. Nemsio is a self-contained utility in its own library, while this repo is an amalgamation of a bunch of miscellaneous routines.

I know it's not ideal, but I think the most straight-forward solution is to put gblevents into its own repo. With that w3emc would lose its NetCDF, Nemsio, Sigio, sp, and bufr dependencies.

**Comment by edwardhartnett** [comment]
OK let's ponder that over the weekend but perhaps its the only way forward. That would not be great - we are trying to reduce the number of libraries...

**Comment by Hang-Lei-NOAA** [comment]
Kyle's suggestion is the way that we try to do many times.
Mark try to so do long time ago.
I try to send the gblevent.f to obspro group in 2015. (When dennis.keyser
was the team lead)
Finally, they all refused to do so, for they cannot handle it.
Now, many people leave, new people in. They will say they cannot handle it.

**Comment by kgerheiser** [comment]
What is there to handle? You load a module called `gblevents` which sets whatever they variables need in their build system and you're done.

**Comment by aerorahul** [comment]
my 2 cents, move it to ufs_utils or in one of the ObsProc utilities (not NCEPLIBS-bufr).

**Comment by kgerheiser** [comment]
What are ObsProc utilities?

**Comment by aerorahul** [comment]
can't show you right now, but they are here:
https://vlab.noaa.gov/ ... ObsProc_global
vlab is migrating to the cloud.  I'll update the link here when it is back.

**Comment by Hang-Lei-NOAA** [comment]
The ideal place is the obspro prep. This code is the core part of prep. The
rest of prep just read in, regression and read out datas.
It needs some enforce order to make it.

**Comment by kgerheiser** [comment]
That does seem to be a better solution if we can do that.

**Comment by edwardhartnett** [comment]
This will be moved to UFS_UTILS. Then we need a new release.

**Comment by edwardhartnett** [comment]
@kgerheiser and @Hang-Lei-NOAA has this been move to UFS_UTILS yet?

**Comment by kgerheiser** [comment]
Waiting for final approval by @GeorgeGayno-NOAA 

https://github.com/NOAA-EMC/UFS_UTILS/pull/536

**Comment by Hang-Lei-NOAA** [comment]
We did not have a simple unit test available at this time.

**Comment by edwardhartnett** [comment]
We don't need to wait for unit tests. We have none for this code now, and we are not likely to get any soon. ;-)

**Comment by edwardhartnett** [comment]
gblevents has been moved to UFS_UTILS, and a new release done.

Has it been removed from this repo?

**Comment by Hang-Lei-NOAA** [comment]
Yes, it's done.

**Comment by edwardhartnett** [comment]
So can we close this issue?

And then we need to do a release...

**Comment by kgerheiser** [comment]
Done
