### ISSUE TITLE
Upgrade doxygen documentation, turn on WARN_AS_ERROR and resolve warnings.

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-w3emc#77]
THe doxygen documentation of this repo needs work.

We need to add doxygen builds to the CI and turn on doxygen warnings.

Then we need to get doxygen building warning-free.

**Comment by edwardhartnett** [comment]
Actually we are already building docs in CI. Are there warnings? I don't see them. Perhaps we need to mess with the doxyfile settings...

**Comment by edwardhartnett** [comment]
There are ~200 files in the src directory. If each takes about 40 minutes of effort, that's a total of ~133 hours of effort.

A reasonable approach would be to spend about 2 hours a day on doxygen, in which case the whole repo should have good documentation in about 67 days of effort.

So it seems like this should be done by the end of September ...

**Comment by edwardhartnett** [comment]
There are ~200 files in the src directory. If each takes about 40 minutes of effort, that's a total of ~133 hours of effort.

A reasonable approach would be to spend about 2 hours a day on doxygen, in which case the whole repo should have good documentation in about 67 days of effort.

So it seems like this should be done by the end of September ...

**Comment by edwardhartnett** [comment]
There are ~200 files in the src directory. If each takes about 40 minutes of effort, that's a total of ~133 hours of effort.

A reasonable approach would be to spend about 2 hours a day on doxygen, in which case the whole repo should have good documentation in about 67 days of effort.

So it seems like this should be done by the end of September ...

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA, we are going to get some help from @BrianCurtis-NOAA on doxygenating this repo. You can continue with g2; when that is complete, you can jump in here on w3emc, but will have to coordinate with Brian so you are not each doing the same file at the same time.

Meanwhile, Brian will get started here and list you and me as reviewers.

**Comment by Hang-Lei-NOAA** [comment]
Okay, I have been doing some long documentation files, But will accelerate
now in the short files. Try to finish G2 in this week.

**Comment by edwardhartnett** [comment]
OK, meanwhile @BrianCurtis-NOAA will start on w3emc and @kgerheiser will start on ip. Soon we will all have good documenation and we'll each move on to testing...

**Comment by edwardhartnett** [comment]
@BrianCurtis-NOAA do we have more doxygenated files for this repo coming soon?

**Comment by BrianCurtis-NOAA** [comment]
@edwardhartnett Yes, sir.

**Comment by BrianCurtis-NOAA** [comment]
WARN_AS_ERROR is set to YES in the doxyfile, and the doxygen is done. This can be closed.

**Comment by edwardhartnett** [comment]
Great work! Having done this for several other NCEPLIBS repos - I know how hard it can be! ;-)
