### ISSUE TITLE
Fix doxygen documentation for getgbens()

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-w3emc#80]
As we see here:
https://noaa-emc.github.io/NCEPLIBS-w3emc/getgbens_8f.html

the documentation for getgbens() needs work.

* must be lower-cased
* parameters are missing documentation
* large block of text contains elements that would be best formatted as lists or tables

@Hang-Lei-NOAA this would be a good place to start.

THis is part of #77.

**Comment by Hang-Lei-NOAA** [comment]
thanks Edward！

**Comment by edwardhartnett** [comment]
This has been fixed.
