### ISSUE TITLE
Update doxyfile for version of doxygen used by CI, turn on some settings...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-w3emc#81]
The doxyfile is generated by cmake from docs/doxyfile.in. Variables in doxyfile.in like @VERSION@ are replaced with the appropriate values by cmake.

We need to:
* learn the version of doxygen used by GitHub CI.
* get on a machine with that exact version of doxygen (or install that version).
* cd docs and run doxygen -u Doxyfile.in to update the Doxyfile.in file. This will add some settings and comments.
* push changes and submit PR with new Doxyfile.in.

The end result will be an updated doxyfile.in, which includes some new fields.

See https://github.com/NOAA-EMC/UFS_UTILS/pull/418 for an example.

Then, we want to set the following:

- set REFERENCED_BY_RELATION = YES if you want the documentation for each subprogram to include a list of which other subprograms call it
- set REFERENCES_RELATION = YES if you want the documentation for each subprogram to include a list of which other subprograms it calls

**Comment by kgerheiser** [comment]
Why does the Doxygen version matter, or rather why does it have to be the same version?
