### ISSUE TITLE
NCO reported wgrib2 in MPMD-style parallel issue

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/NCEPLIBS-w3emc#99]
Diane Stokes from NCO reported following: 
A couple of users have reported trouble running wgrib2 in MPMD-style parallel scripting on Acorn.   suspect a conflict with the mpi build of wgrib2 and parallel processing of the scripts that call it.  Scott Scallion of MDL suspects the same.  He reports: 

I am running into an issue submitting an mpmd job of 4 tasks.  I get the following errors:

[PE_0]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 1: Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 2: Fri Jul 30 14:50:31 2021: [PE_2]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_2]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 3: Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_init:_pmi_inet_info_init returned -1

Notice that the error messages for the third task do not match the other three.  This is the task that hangs and will not complete, until the job hits the wallclock or is qdel by hand.

/lfs/h1/mdl/ptmp/Scott.Scallion/mpmd-serial-job/wgrib2_mpmd.o35907

Diane highly suspect this is related to MPI build with the wgrib2/2.0.8 module.

**Comment by Hang-Lei-NOAA** [comment]
Following Wesleys' suggestions, that this would be a issue of using serial netcdf and parallel netcdf in builds.
We put 7 combinations of different serial netcdf and different iploates builds from NCEPLIBS-w3emc repo for users to locate the problem.

module use /lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/NCEPLIBS-wgrib2/modulefiles
module avail

--------------------------------------------------------------------------------- /lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/NCEPLIBS-wgrib2/modulefiles ---------------------------------------------------------------------------------
   wgrib2/2.0.81 (L)    wgrib2/2.0.82    wgrib2/2.0.83    wgrib2/2.0.84    wgrib2/2.0.85    wgrib2/2.0.86    wgrib2/2.0.87
Then module load one of them.

wgrib2/2.0.81: default from the wgrib2.0.8 repo.
wgrib2/2.0.82: build use netcdf 3 option with netcdf4.7.4 lib, and ip2 lib.
wgrib2/2.0.83: build use netcdf 4 option with netcdf4.7.4 lib, and ip2 lib.
wgrib2/2.0.84: build use netcdf 3 option with netcdf4.7.4 lib, and ip lib.
wgrib2/2.0.85: build use netcdf 4 option with netcdf4.7.4 lib, and ip lib.
wgrib2/2.0.86: build use netcdf 3 option with netcdf3.6.3 lib, and ip lib.
wgrib2/2.0.86: build use netcdf 3 option with netcdf3.6.3 lib, and ip2 lib.

**Comment by Hang-Lei-NOAA** [comment]
Guang's tests shows that non of this solved the MDMP issue. Therefore, we need to explore new approach to locate the issue.

**Comment by Hang-Lei-NOAA** [comment]
Pass it to Kyle for using Wesley's original wgrib2 package.

**Comment by kgerheiser** [comment]
Wrong repo
